[workspace]
members = [
  "xds",
  "registry",
  "registry-zookeeper",
  "registry-nacos",
  "metadata",
  "common",
  "config",
  "dubbo",
  "examples/echo",
  "examples/greeter",
  "dubbo-build",
  "extension","nacos-extension","extension-loader"
]
