[workspace]
resolver = "2"
members = [
  "dubbo",
]


[workspace.dependencies]
pin-project = "1"
tokio = "1.0"
tokio-stream = "0.1"
tokio-util = "0.7"
tower = "0.4"
async-trait = "0.1"
futures = "0.3"
urlencoding = "2.1.2"
thiserror = "1"
itertools = "0.12"
bytes = "1.0"
url = "2.5.0"
tracing = "0.1.40"

